const urlManager = {
    databases: {
        mongodbUrl_local: "mongodb://localhost:27017/connector_app?replicaSet=rs0",
        mongodbUrl_server: "mongodb://root:YHou7d4xMfV8Ew1qBxQVNhZIN8UWhzKncrfXdyviKEV5C0d1Aeydu40FfPHcYXH4@147.93.155.125:5432/connector_production_app?directConnection=true&authSource=admin",
        mongodbUrl_staging: "mongodb://root:fecoqB7SwygNMWZsFTj48g1I8z0Ux2mRFqI71b0Ikpc4Oil5j3EA2M2pgIhwbaIB@147.93.168.64:5432/connector_staging_app?directConnection=true&authSource=admin",
    },
    whatsappDatabases: {
        mongodbUrl_local: "mongodb://localhost:27017/whatsapp_app?replicaSet=rs0",
        mongodbUrl_server: "mongodb://root:YHou7d4xMfV8Ew1qBxQVNhZIN8UWhzKncrfXdyviKEV5C0d1Aeydu40FfPHcYXH4@147.93.155.125:5432/whatsapp_production_app?directConnection=true&authSource=admin",
        mongodbUrl_staging: "mongodb://root:fecoqB7SwygNMWZsFTj48g1I8z0Ux2mRFqI71b0Ikpc4Oil5j3EA2M2pgIhwbaIB@147.93.168.64:5432/whatsapp_staging_app?directConnection=true&authSource=admin",
    },
    redis: {
        connectionUrl_local: {
            host: "82.180.144.141",
            port: "5434",
            password: "qNy8TQEm7JbPO6b5X9lhsB9GRRZY2HzGvafUlRmeseMmU0NNTP46ueYZWKcovAoy",
        },
        connectionUrl_server: {
            host: '147.93.155.125',
            port: '5420',
            password: "XtqFsx5VT3ig8jvSyIbtt9PpTWdIg8SwPfiafgIsCzJlY5LQWadwJ59dzcMWh7y5",
        },
        connectionUrl_staging: {
            host: "147.93.168.64",
            port: "5434",
            password: "XOVANLnrMUGENjMZxuL0kk8E3cSk6yL2l7RCrw3yBAwAlnQ80muiZVeab9oeil9d",
        },
    },
    internalApiKey: 'h.b1yFVrh,<xMM=<%HYJ3@yx&)>at^d@OquyM"LLCnYdy=BZ0/8sK<MwDK#zBGCn',
    api_server_url: {
        lms_user: "https://adminapis.backendprod.com/lms_user/api",
        lms_chat: "https://adminapis.backendprod.com/lms_chat/api",
        lms_campaign: "https://adminapis.backendprod.com/lms_campaign/api",
        lms_cc: "https://adminapis.backendprod.com/chat_and_campaign/api",
        app_url: "https://metagraph.backendprod.com",
        onboard_app: "https://onboardadmin.backendprod.com",
        html_to_pdf: "https://htmltopdf.emovur.com",
        global_user: "https://gateway.pointofconnect.com",
        pc_onboard_url: "https://onboard.backendprod.com",
        bot_app_url: "https://botadmin.backendprod.com",
        wallet_app: "https://walletadmin.backendprod.com",
        webhook_app: "https://webhookadmin.backendprod.com",
        chat_app: "https://chatadmin.backendprod.com/api",
    },
    api_staging_url: {
        lms_user: "https://adminstaging.backendprod.com/lms_user/api",
        lms_chat: "https://adminstaging.backendprod.com/lms_chat/api",
        lms_campaign: "https://adminstaging.backendprod.com/lms_campaign/api",
        lms_cc: "https://adminstaging.backendprod.com/chat_and_campaign/api",
        app_url: "https://metagraphstaging.backendprod.com",
        onboard_app: "https://onboardstaging.backendprod.com",
        html_to_pdf: "https://htmltopdf.emovur.com",
        global_user: "https://gateway-staging.emovur.com",
        pc_onboard_url: "https://onboard.backendprod.com",
        bot_app_url: "https://botstaging.backendprod.com",
        wallet_app: "https://walletstaging.backendprod.com",
        webhook_app: "http://localhost:5050",
        chat_app: "https://chatstaging.backendprod.com/api",
    },
    api_local_url: {
        lms_user: "http://localhost/lms_user/api",
        lms_chat: "http://localhost/chat_and_campaign/lms_chat/api",
        lms_campaign: "http://localhost/chat_and_campaign/lms_campaign/api",
        lms_cc: "http://localhost/chat_and_campaign/api",
        app_url: "http://localhost:5555",
        onboard_app: "http://localhost:5500",
        html_to_pdf: "https://htmltopdf.emovur.com",
        global_user: "https://gateway-staging.emovur.com",
        pc_onboard_url: "http://localhost/chat_and_campaign/partner_app",
        bot_app_url: "http://localhost:3030",
        wallet_app: "http://localhost:5000",
        webhook_app: "https://webhookadmin.backendprod.com",
        chat_app: "http://localhost:3330/api",
    },
};

export default urlManager;
